# Generated by Django 4.1 on 2023-07-14 02:19

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_almacen', models.CharField(max_length=20)),
                ('prefijo', models.CharField(max_length=5)),
                ('telefono_fijo', models.CharField(max_length=30)),
                ('telefono_celular', models.CharField(max_length=30)),
                ('direccion_almacen', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=30)),
                ('estado_almacen', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=1)),
            ],
            options={
                'permissions': [('add_almacen', 'Puede crear almacen'), ('change_almacen', 'Puede modificar almacen'), ('delete_almacen', 'Puede eliminar almacen'), ('view_almacen', 'Puede ver los almacenes')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_articulo', models.CharField(max_length=20)),
                ('nombre_articulo', models.CharField(max_length=30)),
                ('nombre_largo_articulo', models.CharField(max_length=250)),
                ('estado_articulo', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100, unique=True)),
                ('nick_empresa', models.CharField(max_length=100, unique=True)),
                ('nit', models.CharField(max_length=10, unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('representante_legal', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono_fijo', models.CharField(max_length=14)),
                ('telefono_celular', models.CharField(max_length=14)),
                ('direccion_principal', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=30)),
                ('regimen', models.CharField(choices=[('1', 'Común'), ('0', 'Simplificado')], default='1', max_length=1)),
                ('estado_empresa', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=1)),
                ('vigencia', models.DateField(default=datetime.date.today)),
            ],
            options={
                'permissions': [('add_empresa', 'Puede crear empresa'), ('change_empresa', 'Puede modificar empresa'), ('view_empresa', 'Puede ver las empresas')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ListaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('moneda', models.CharField(max_length=3)),
                ('estado_listaprecios', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unidad_medida', models.CharField(max_length=30)),
                ('nombre_unidad_medida', models.CharField(max_length=30)),
                ('estado_categoria', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa')),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='NivelesInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximo', models.DecimalField(decimal_places=4, max_digits=5)),
                ('minimo', models.DecimalField(decimal_places=4, max_digits=5)),
                ('reorden', models.DecimalField(decimal_places=4, max_digits=5)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.almacen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa')),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='ListaPreciosArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=5)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=5)),
                ('descripcion', models.CharField(max_length=20, unique=True)),
                ('estado_listaprecios', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa')),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.articulo')),
                ('id_lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.listaprecios')),
                ('id_presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='ListaPreciosAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_listaprecios_almacen', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa')),
                ('id_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.almacen')),
                ('id_lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.listaprecios')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoAlterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_articulo', models.CharField(max_length=20)),
                ('posicion', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=1)),
                ('descripcion', models.CharField(max_length=30)),
                ('estado_codigoalterno', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa')),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.articulo')),
                ('listaPrecio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.listaprecios')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=30)),
                ('estado_categoria', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=1)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='atpos.categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estante', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa')),
                ('id_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.almacen')),
            ],
        ),
        migrations.CreateModel(
            name='BaseIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_iva', models.DecimalField(decimal_places=4, max_digits=7)),
                ('nombre_base_iva', models.CharField(max_length=30)),
                ('estado_baseiva', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='base_iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.baseiva'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.unidadmedida'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('add_usuario', 'Puede crear usuario'), ('change_usuario', 'Puede modificar usuario'), ('delete_usuario', 'Puede eliminar usuario'), ('view_usuario', 'Puede ver los usuario'), ('password_usuario', 'Puede cambiar la clave usuario')],
                'default_permissions': (),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(max_length=5)),
                ('tipo_factura', models.CharField(choices=[('0', 'Pos'), ('1', 'Electrónica'), ('2', 'Combinada')], default='0', max_length=1)),
                ('estado', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=1)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.almacen')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa')),
            ],
            options={
                'permissions': [('add_caja', 'Puede crear caja'), ('change_caja', 'Puede modificar caja'), ('delete_caja', 'Puede eliminar caja'), ('view_caja', 'Puede ver las cajas')],
                'default_permissions': (),
                'unique_together': {('prefijo', 'empresa')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='almacen',
            unique_together={('prefijo', 'empresa')},
        ),
    ]
