# Generated by Django 4.1 on 2023-07-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atpos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tel_inicial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
