# Generated by Django 4.1 on 2023-08-10 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atpos', '0003_permisoempresa_grupoempresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'default_permissions': (), 'permissions': [('add_articulo', 'Artículo crear'), ('change_articulo', 'Artículo modificar'), ('view_articulo', 'Artículo ver'), ('delete_articulo', 'Artículo borrar')]},
        ),
    ]
