# Generated by Django 4.1 on 2023-08-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atpos', '0004_alter_articulo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'default_permissions': (), 'permissions': [('add_almacen', 'Almacén crear'), ('change_almacen', 'Almacén modificar'), ('delete_almacen', 'Almacén borrar'), ('view_almacen', 'Almacén ver')]},
        ),
        migrations.AlterModelOptions(
            name='caja',
            options={'default_permissions': (), 'permissions': [('add_caja', 'Caja crear'), ('change_caja', 'Caja modificar'), ('delete_caja', 'Caja eliminar'), ('view_caja', 'Caja ver')]},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'default_permissions': (), 'permissions': [('add_usuario', 'Usuario crear'), ('change_usuario', 'Usuario modificar'), ('delete_usuario', 'Usuario eliminar'), ('view_usuario', 'Usuario ver'), ('password_usuario', 'Puede cambiar la clave usuario')]},
        ),
        migrations.AlterUniqueTogether(
            name='almacen',
            unique_together={('empresa', 'nombre_almacen', 'prefijo')},
        ),
    ]
