# Generated by Django 4.1 on 2023-08-20 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atpos', '0005_alter_almacen_options_alter_caja_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_caja', models.IntegerField()),
                ('estado', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=1)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atpos.almacen')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atpos.empresa')),
            ],
            options={
                'permissions': [('add_cajaserie', 'CajaSerie crear'), ('change_cajaserie', 'CajaSerie modificar'), ('delete_cajaserie', 'CajaSerie eliminar'), ('view_cajaserie', 'CajaSerie ver')],
                'default_permissions': (),
                'unique_together': {('numero_caja', 'almacen', 'empresa')},
            },
        ),
    ]
