# Generated by Django 4.1 on 2023-08-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atpos', '0007_alter_baseiva_options_alter_unidadmedida_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombre_largo_articulo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
