# Generated by Django 4.1 on 2023-08-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atpos', '0009_alter_articulo_base_iva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaprecios',
            options={'default_permissions': (), 'ordering': ['nombre'], 'permissions': [('add_listaprecios', 'Lista precios crear'), ('change_listaprecios', 'Lista precios modificar'), ('delete_listaprecios', 'Lista precios eliminar'), ('view_listaprecios', 'Lista precios ver')]},
        ),
        migrations.AlterUniqueTogether(
            name='listaprecios',
            unique_together={('nombre', 'empresa')},
        ),
    ]
