# Generated by Django 4.1 on 2023-08-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atpos', '0011_rename_estado_almacen_almacen_estado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unidadmedida',
            unique_together={('codigo_unidad_medida', 'empresa')},
        ),
    ]
