# Generated by Django 4.1 on 2023-08-29 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atpos', '0014_alter_codigoalterno_precio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articulo',
            unique_together={('codigo_articulo', 'empresa')},
        ),
    ]
