# Generated by Django 4.1 on 2023-08-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atpos', '0015_alter_articulo_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigoalterno',
            options={'default_permissions': (), 'permissions': [('add_codigoalterno', 'Código Alterno crear'), ('change_codigoalterno', 'Código Alterno modificar'), ('view_codigoalterno', 'Código Alterno ver'), ('delete_codigoalterno', 'Código Alterno borrar')]},
        ),
        migrations.AlterField(
            model_name='codigoalterno',
            name='listaPrecio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atpos.listaprecios'),
        ),
        migrations.AlterUniqueTogether(
            name='codigoalterno',
            unique_together={('codigo_articulo', 'empresa')},
        ),
    ]
