# Generated by Django 4.1 on 2023-08-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atpos', '0016_alter_codigoalterno_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigoalterno',
            old_name='id_articulo',
            new_name='articulo',
        ),
    ]
