# Generated by Django 4.1 on 2023-09-16 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atpos', '0017_rename_id_articulo_codigoalterno_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='base_iva',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='atpos.baseiva'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atpos.categoria'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atpos.unidadmedida'),
        ),
    ]
