# Generated by Django 4.1 on 2023-09-23 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atpos', '0018_alter_articulo_base_iva_alter_articulo_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigoalterno',
            old_name='descripcion',
            new_name='nombre_articulo',
        ),
        migrations.RenameField(
            model_name='codigoalterno',
            old_name='codigo_articulo',
            new_name='nuevo_codigo_articulo',
        ),
        migrations.AlterUniqueTogether(
            name='codigoalterno',
            unique_together={('nuevo_codigo_articulo', 'empresa')},
        ),
        migrations.AlterField(
            model_name='codigoalterno',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atpos.articulo'),
        ),
        migrations.AlterField(
            model_name='codigoalterno',
            name='listaPrecio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atpos.listaprecios'),
        ),
    ]
